### ISSUE TITLE
WARNING in ./~/@angular/core/@angular/core.es5.js 5870:15-36

### ISSUE THREAD

**Issue by dimalakh** [sujeetkrjaiswal/angular4-starter#1]
solution: 
in your config/webpack.common.js 
replace line /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/ 
with this line /angular(\\|\/)core(\\|\/)@angular/

**Comment by sujeetkrjaiswal** [comment]
used the provided solution. Thanks :+1:
